config/routes.rb
# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)
#   resources :nodes
#   resources :places
#   resources :images
#   resources :cities do
#     collection do
#       get :get_cities
#     end
#   end

#   resources :states do
#     collection do
#       get :get_states
#     end
#   end 
#   resources :countries
#   resources :regions
#   resources :user_regions
#   resources :user_roles
#   devise_for :users
#   resources :companies
#   resources :managers 
#   root'companies#index'
 
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  resources :regions do
    member do 
      get :edit_region
      get :show_page
      post :comments
      put "like", to: "regions#upvote"
      put "dislike", to: "regions#downvote"
    end
  end

  resources :nodes do
    member do 
      get :edit_node
    end 
    member do
      get :show_page
    end
   end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :places do
    member do 
      get :edit_place
      get :show_page
      post :comments
      put "like", to: "places#upvote"
      put "dislike", to: "places#downvote"
    end
  end

  resources :images do
    collection do 
      get :login_page
    end 
  end
  

  resources :cities do
    collection do
      get :get_cities
    end
    member do
      get :show_page
      get :edit_city
      post :comments
      put "like", to: "cities#upvote"
      put "dislike", to: "cities#downvote"
    end
  end 

  resources :states do
    collection do
      get :get_states
    end
    member do 
      get :edit_state
      get :show_page
      post :comments
      put "like", to: "states#upvote"
      put "dislike", to: "states#downvote"
    end
  end 

  resources :countries do
    member do
      get :edit_country
      get :show_page
      post :comments
      put "like", to: "countries#upvote"
      put "dislike", to: "countries#downvote"
    end
  end

  resources :user_regions do
    member do 
      get :edit_user_region
      get :show_page
      post :comments
       put "like", to: "user_regions#upvote"
      put "dislike", to: "user_regions#downvote"
    end
  end

  resources :user_roles do
   member do 
      get :edit_user_role
      get :show_page
      post :comments
       put "like", to: "user_roles#upvote"
      put "dislike", to: "user_roles#downvote"
    end
  end

  resources :companies do
    resources :comments
     member do
      put "like", to: "companies#upvote"
      put "dislike", to: "companies#downvote"
    end 
  
    member do 
      get :edit_company
      get :show_page
    end 
    
  end
  
  resources :managers do
    member do
      get :show_page
      get :edit_manager
      
    end
  end

 resources :comments, only: [] do
   member do 
     put "like", to: "comments#upvote" 
     put "dislike", to: "comments#downvote" 
    end 
  end
  

  devise_for :users
  root 'companies#index'
  # get 'get_states' => "states#get_states"
  #  get 'get_cities' => "cities#get_cities"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/city.rb
class City < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  acts_as_votable
  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
	
	acts_as_commentable
	acts_as_votable
     #has_many :comments
	has_many :countries
	has_many :states
	has_many :cities
end

app/models/country.rb
class Country < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_many :states
	has_many :cities
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, :polymorphic => true
	mount_uploader :image_name, ImageUploader
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_one :node
	attr_accessor :node_name
end

app/models/region.rb
class Region < ApplicationRecord
	acts_as_commentable
   acts_as_votable
 has_many :regions, through: :user_regions 
  has_many :users, through: :user_regions

end

app/models/state.rb
class State < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_many :cities
end

app/models/user.rb
class User < ApplicationRecord
	has_many :regions, through: :user_regions 
	has_many :images, :as=> :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy,:show_page,:edit_state]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @commentable=State.find(params[:id])
    @comment=Comment.new
  end
   def show_page
    render 'states/show_page' 
   end
  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  def upvote
   @state = State.find(params[:id])
    @state.upvote_by current_user
    respond_to do |format|
      format.js { render :file=>  'states/states.js.erb'}
    end
  end

  def downvote
   @state = State.find(params[:id])
    @state.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :file=> 'states/states.js.erb'}
    end
   end


  def comments
    @commentable=State.find(params[:id])
    @comment=@commentable.comments.create(comment_params)
    @comment.save
    redirect_to state_path
  end
  def edit_state
    render 'states/edit_state'
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        @states=State.all
        format.js { render :file=>'states/update_states.js.erb', notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def get_states
    @states= State.where(:country_id=>params[:country])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_state
    @state = State.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end

    
  def state_params
   params.require(:state).permit(:state_name, :country_id)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="Container">
 <%= form_for(state, :remote=>true) do |f| %>
  
   <% if state.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

       <ul>
         <% state.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
     </div>
   <% end %>
  

    <div class="form-group">
      <label class="col-sm-2 control-label">State_Name</label>
      <div class="col-sm-6  inputGroupContainer">
        
       <%= f.text_field :state_name, :placeholder=>"StateName", :class=>"form-control",required: true %>
      </div>
    </div><br><br><br>

    <div class="form-group">
      <label class="col-sm-2 control-label">Country</label>
      <div class="col-sm-3  inputGroupContainer">
        <%=f.select(:country_id, Country.all.collect {|u| [u.country_name, u.id]},{},:prompt => "Select Country", :class=>"form-control") %>
      </div>
    </div><br><br><br>

  
   <div class="form-group">
      <label class="col-sm-2 control-label"></label>
      <div class="col-sm-3">
        <%=f.submit :class=>"btn btn-success" %>
      </div>
    </div><br><br>
  <% end %>
</div>

app/views/states/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="state-container">
<h1>States</h1>

<table class="table">
  <thead>
    <tr>
      <th>State name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.state_name %></td>
        <td><%= state.country_id %></td>
        <td><%= link_to 'Show', show_page_state_path(state),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit', edit_state_state_path(state),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/states/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State name:</strong>
  <%= @state.state_name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @state.country_id %>
</p>

app/views/states/_state_select.html.erb
<select id="company_state_id" name="company[state_id]"><option value="">Select State</option>
<% @states.each do |state| %>
   <option value="<%= state.id%>"><%= state.state_name%></option>
<%end%>
</select>

<script>
$(document).ready(function() {
$('#company_state_id').change(function(){
  var state =  $('#company_state_id').val()
  $.ajax({
    url:" /cities/get_cities",
    type: "GET",
    data: {state: state},
  });
});
});
</script>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/edit_state.js.erb
$('.modal-body').html('<%= escape_javascript(render "form", state: @state )%>');

app/views/states/get_states.js.erb
$('.statecontainer').html('<%= escape_javascript( render "states/state_select")%>');

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>
<div class="state-container">
<h1>States</h1>

<table class="table">
  <thead>
    <tr>
      <th>State name</th>
      <th>Country</th>
       <th>Like</th>
        <th>disLike</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.state_name %></td>
        <td><%= state.country_id %></td>
         <div class="col-md-6">
          <div class="btn-group pull-right" style="">
         <td><%= link_to like_state_path(state), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
          <span class="glyphicon glyphicon-thumbs-up state-up-<%=state.id%>" style='width: 50px' >
             <%= state.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_state_path(state), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
          <span class="glyphicon glyphicon-thumbs-down state-down-<%=state.id%>" style='width: 50px'>
           <%= state.get_downvotes.size %><% end %></td>
          </span>
      </div>
    </div>



         
        <td><%= link_to 'Show',  show_page_state_path(state),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit', edit_state_state_path(state),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path,:class=>"btn btn-success" %>
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title">User Detials Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>
 
 <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title"> update User Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>

app/views/states/new.html.erb
<center><h1>New State</h1></center>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path,:class=>"btn btn-info" %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State name:</strong>
  <%= @state.state_name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @state.country_id %>
</p>

<h2>Comments</h2>

<% @state.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body%>
  </p> 
  <div class="btn-group pull-right">
         <td><%= link_to like_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-up comment-up-<%=comment.id%>" style='width: 50px'>
             <%= comment.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-down comment-down-<%=comment.id%>" style='width: 50px'>
           <%= comment.get_downvotes.size %><% end %></td>
          </span>
      </div> 
<%end%>

<h2>Add a comment:</h2>

<%= form_for @comment, :url =>comments_state_path , :method =>"post"  do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter%>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>

app/views/states/show_page.js.erb
$(".modal-body").html("<%= escape_javascript(render 'states/show') %>");

app/views/states/states.js.erb
$(function() 
	{ $('.state-up-<%=@state.id%>').text("<%= @state.get_upvotes.size %>");
 $('.state-down-<%=@state.id%>').text("<%= @state.get_downvotes.size %>"); });

app/views/states/update_states.js.erb
$('.state-container').html('<%= escape_javascript( render "states/index")%>');
$("#myModal1").modal('hide');