config/routes.rb
# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)
#   resources :nodes
#   resources :places
#   resources :images
#   resources :cities do
#     collection do
#       get :get_cities
#     end
#   end

#   resources :states do
#     collection do
#       get :get_states
#     end
#   end 
#   resources :countries
#   resources :regions
#   resources :user_regions
#   resources :user_roles
#   devise_for :users
#   resources :companies
#   resources :managers 
#   root'companies#index'
 
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  resources :regions do
    member do 
      get :edit_region
      get :show_page
      post :comments
      put "like", to: "regions#upvote"
      put "dislike", to: "regions#downvote"
    end
  end

  resources :nodes do
    member do 
      get :edit_node
    end 
    member do
      get :show_page
    end
   end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :places do
    member do 
      get :edit_place
      get :show_page
      post :comments
      put "like", to: "places#upvote"
      put "dislike", to: "places#downvote"
    end
  end

  resources :images do
    collection do 
      get :login_page
    end 
  end
  

  resources :cities do
    collection do
      get :get_cities
    end
    member do
      get :show_page
      get :edit_city
      post :comments
      put "like", to: "cities#upvote"
      put "dislike", to: "cities#downvote"
    end
  end 

  resources :states do
    collection do
      get :get_states
    end
    member do 
      get :edit_state
      get :show_page
      post :comments
      put "like", to: "states#upvote"
      put "dislike", to: "states#downvote"
    end
  end 

  resources :countries do
    member do
      get :edit_country
      get :show_page
      post :comments
      put "like", to: "countries#upvote"
      put "dislike", to: "countries#downvote"
    end
  end

  resources :user_regions do
    member do 
      get :edit_user_region
      get :show_page
      post :comments
       put "like", to: "user_regions#upvote"
      put "dislike", to: "user_regions#downvote"
    end
  end

  resources :user_roles do
   member do 
      get :edit_user_role
      get :show_page
      post :comments
       put "like", to: "user_roles#upvote"
      put "dislike", to: "user_roles#downvote"
    end
  end

  resources :companies do
    resources :comments
     member do
      put "like", to: "companies#upvote"
      put "dislike", to: "companies#downvote"
    end 
  
    member do 
      get :edit_company
      get :show_page
    end 
    
  end
  
  resources :managers do
    member do
      get :show_page
      get :edit_manager
      
    end
  end

 resources :comments, only: [] do
   member do 
     put "like", to: "comments#upvote" 
     put "dislike", to: "comments#downvote" 
    end 
  end
  

  devise_for :users
  root 'companies#index'
  # get 'get_states' => "states#get_states"
  #  get 'get_cities' => "cities#get_cities"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_role.rb
class UserRole < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :set_user_role, only: [:show, :edit, :update, :destroy,:show_page,:edit_user_role]

  # GET /user_roles
  # GET /user_roles.json
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1
  # GET /user_roles/1.json
  def show
   @commentable=UserRole.find(params[:id])
   @comment=Comment.new
  end

     
  def show_page
    render 'user_roles/show_page' 
  end

 def upvote
   @user_role = UserRole.find(params[:id])
   @user_role.upvote_by current_user
   respond_to do |format|
      format.js { render :file=> 'user_roles/user_roles.js.erb'}
    end
  end

  def downvote
   @user_role = UserRole.find(params[:id])
    @user_role.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :file=> 'user_roles/user_roles.js.erb'}
    end
  end 
  
  # GET /user_roles/new
  def new
    @user_role = UserRole.new
  end

  # GET /user_roles/1/edit
  def edit
  end
  def comments
    @commentable=UserRole.find(params[:id])
    @comment=@commentable.comments.create(comment_params)
    @comment.save
    redirect_to user_role_path
  end

  def edit_user_resion
    render 'user_roles/edit_user_role'
  end

  # POST /user_roles
  # POST /user_roles.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to @user_role, notice: 'User role was successfully created.' }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_roles/1
  # PATCH/PUT /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        @user_roles = UserRole.all
        format.js { render :file=>'user_roles/update_user_roles.js.erb', notice: 'User role was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1
  # DELETE /user_roles/1.json
  def destroy
    @user_role.destroy
    respond_to do |format|
      format.html { redirect_to user_roles_url, notice: 'User role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_role_params
      params.require(:user_role).permit(:role_name)
    end
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/user_roles/_form.html.erb
<%= form_for(user_role, :remote=>true) do |f| %>
  <% if user_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_role.errors.count, "error") %> prohibited this user_role from being saved:</h2>

      <ul>
      <% user_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_name %>
    <%= f.text_field :role_name,required: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_roles/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="user_role-container">

<h1>User Roles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Role name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_roles.each do |user_role| %>
      <tr>
        <td><%= user_role.role_name %></td>
        <td><%= link_to 'Show',  show_page_user_role_path(user_role),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>
 
        <td><%= link_to 'Edit',  edit_user_role_user_role_path(user_role),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', user_role, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/user_roles/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @user_role.role_name %>
</p>

app/views/user_roles/edit.html.erb
<h1>Editing User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Show', @user_role %> |
<%= link_to 'Back', user_roles_path %>

app/views/user_roles/edit_user_role.js.erb
$('.modal-body').html('<%= escape_javascript(render "form", user_role: @user_role )%>');

app/views/user_roles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="user_role-container">
<h1>User Roles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Role name</th>
      <th>Like</th>
      <th>DisLike</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_roles.each do |user_role| %>
      <tr>
        <td><%= user_role.role_name %></td>

        <div class="col-md-6">
         <div class="btn-group pull-right" style="">
           <td><%= link_to like_user_role_path(user_role), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
            <span class="glyphicon glyphicon-thumbs-up user_role-up-<%=user_role.id%>" style='width: 50px' >
             <%= user_role.get_upvotes.size %> <% end %></td>
            </span>

           <td><%= link_to dislike_user_role_path(user_role), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
           <span class="glyphicon glyphicon-thumbs-down user_role-down-<%=user_role.id%>" style='width: 50px'>
             <%= user_role.get_downvotes.size %><% end %></td>
           </span>
         </div>
       </div>

        <td><%= link_to 'Show',  show_page_user_role_path(user_role),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td> 
        <td><%= link_to 'Edit',edit_user_role_user_role_path(user_role),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', user_role, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Role', new_user_role_path,:class=>"btn btn-success" %>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title">User Role Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>
 
 <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title"> update User Role Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>

app/views/user_roles/new.html.erb
<h1>New User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Back', user_roles_path %>

app/views/user_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @user_role.role_name %>
</p>
<h2>Comments</h2>

<% @user_role.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body%>
  </p> 
  <div class="btn-group pull-right">
         <td><%= link_to like_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-up comment-up-<%=comment.id%>" style='width: 50px'>
             <%= comment.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-down comment-down-<%=comment.id%>" style='width: 50px'>
           <%= comment.get_downvotes.size %><% end %></td>
          </span>
      </div> 
<%end%>

<h2>Add a comment:</h2>

<%= form_for @comment, :url =>comments_user_role_path , :method =>"post"  do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter%>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>
<%= link_to 'Edit', edit_user_role_path(@user_role) %> |
<%= link_to 'Back', user_roles_path %>

app/views/user_roles/show_page.js.erb
$(".modal-body").html("<%= escape_javascript(render 'user_roles/show') %>");

app/views/user_roles/update_user_roles.js.erb
$('.user_role-container').html('<%= escape_javascript( render "user_roles/index")%>');
$("#myModal1").modal('hide');

app/views/user_roles/user_roles.js.erb
$(function() 
	{ $('.user_role-up-<%=@user_role.id%>').text("<%= @user_role.get_upvotes.size %>");
 $('.user_role-down-<%=@user_role.id%>').text("<%= @user_role.get_downvotes.size %>"); });