config/routes.rb
# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)
#   resources :nodes
#   resources :places
#   resources :images
#   resources :cities do
#     collection do
#       get :get_cities
#     end
#   end

#   resources :states do
#     collection do
#       get :get_states
#     end
#   end 
#   resources :countries
#   resources :regions
#   resources :user_regions
#   resources :user_roles
#   devise_for :users
#   resources :companies
#   resources :managers 
#   root'companies#index'
 
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  resources :regions do
    member do 
      get :edit_region
      get :show_page
      post :comments
      put "like", to: "regions#upvote"
      put "dislike", to: "regions#downvote"
    end
  end

  resources :nodes do
    member do 
      get :edit_node
    end 
    member do
      get :show_page
    end
   end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :places do
    member do 
      get :edit_place
      get :show_page
      post :comments
      put "like", to: "places#upvote"
      put "dislike", to: "places#downvote"
    end
  end

  resources :images do
    collection do 
      get :login_page
    end 
  end
  

  resources :cities do
    collection do
      get :get_cities
    end
    member do
      get :show_page
      get :edit_city
      post :comments
      put "like", to: "cities#upvote"
      put "dislike", to: "cities#downvote"
    end
  end 

  resources :states do
    collection do
      get :get_states
    end
    member do 
      get :edit_state
      get :show_page
      post :comments
      put "like", to: "states#upvote"
      put "dislike", to: "states#downvote"
    end
  end 

  resources :countries do
    member do
      get :edit_country
      get :show_page
      post :comments
      put "like", to: "countries#upvote"
      put "dislike", to: "countries#downvote"
    end
  end

  resources :user_regions do
    member do 
      get :edit_user_region
      get :show_page
      post :comments
       put "like", to: "user_regions#upvote"
      put "dislike", to: "user_regions#downvote"
    end
  end

  resources :user_roles do
   member do 
      get :edit_user_role
      get :show_page
      post :comments
       put "like", to: "user_roles#upvote"
      put "dislike", to: "user_roles#downvote"
    end
  end

  resources :companies do
    resources :comments
     member do
      put "like", to: "companies#upvote"
      put "dislike", to: "companies#downvote"
    end 
  
    member do 
      get :edit_company
      get :show_page
    end 
    
  end
  
  resources :managers do
    member do
      get :show_page
      get :edit_manager
      
    end
  end

 resources :comments, only: [] do
   member do 
     put "like", to: "comments#upvote" 
     put "dislike", to: "comments#downvote" 
    end 
  end
  

  devise_for :users
  root 'companies#index'
  # get 'get_states' => "states#get_states"
  #  get 'get_cities' => "cities#get_cities"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/controllers/user_regions_controller.rb
class UserRegionsController < ApplicationController
  before_action :set_user_region, only: [:show, :edit, :update, :destroy,:show_page,:edit_user_region]

  # GET /user_regions
  # GET /user_regions.json
  def index
    @user_regions = UserRegion.all
  end

  # GET /user_regions/1
  # GET /user_regions/1.json
  def show
    
   @commentable=UserRegion.find(params[:id])
   @comment=Comment.new
  end
    
     def upvote
   @user_region = UserRegion.find(params[:id])
    @user_region.upvote_by current_user
    respond_to do |format|
      format.js { render :file=> 'user_regions/user_regions.js.erb'}
    end
  end

  def downvote
   @user_region = UserRegion.find(params[:id])
    @user_region.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :file=> 'user_regions/user_regions.js.erb'}
    end
  end 
  
  def show_page
    render 'user_regions/show_page' 
   end


  # GET /user_regions/new
  def new
    @user_region = UserRegion.new
  end

  # GET /user_regions/1/edit
  def edit
  end 

  def comments
    @commentable=UserRegion.find(params[:id])
    @comment=@commentable.comments.create(comment_params)
    @comment.save
    redirect_to user_region_path
  end

  def edit_user_resion
    render 'user_resions/edit_user_resion'
  end
  # POST /user_regions
  # POST /user_regions.json
  def create
    @user_region = UserRegion.new(user_region_params)
    if params[:user_region][:right_value].present?
      @user_region=UserRegion.find_by_region_id(params[:user_region][:region_id])
      @user_region.destroy
      redirect_to :back
      else
      @user_region = UserRegion.new(user_region_params)
      @user_region.right=true
      # @user_region.left == true
  
     respond_to do |format|
       if @user_region.save
         format.html { redirect_to @user_region, notice: 'User region was successfully created.' }
         format.json { render :show, status: :created, location: @user_region }
         else
         format.html { render :new }
         format.json { render json: @user_region.errors, status: :unprocessable_entity }
       end
      end
    end
  end

  # PATCH/PUT /user_regions/1
  # PATCH/PUT /user_regions/1.json
  def update
    respond_to do |format|
      if @user_region.update(user_region_params)
        @user_regions=UserRegion.all
        format.js { render :file=>'user_regions/update_user_regions.js.erb', notice: 'User region was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_region }
      else
        format.html { render :edit }
        format.json { render json: @user_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_regions/1
  # DELETE /user_regions/1.json
  def destroy
    @user_region.destroy
    respond_to do |format|
      format.html { redirect_to user_regions_url, notice: 'User region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def set_user_region
    @user_region = UserRegion.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end

  
  def user_region_params
    params.require(:user_region).permit(:region_name,:user_id, :region_id,:left,:right)
  end
end

app/helpers/user_regions_helper.rb
module UserRegionsHelper
end

app/views/user_regions/_form.html.erb
  
<div class="asfdf">
 <div class="Container">
   <div class="col-sm-6">
     <%= form_for(user_region, :remote=>true) do |f| %>
        <% if user_region.errors.any? %>
         <div id="error_explanation">
         <h2><%= pluralize(user_region.errors.count, "error") %> prohibited this user_region from being saved:</h2>
          <ul>
          <% user_region.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
        </div>
      <% end %>
  

  <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-6 inputGroupContainer">
        <%=f.select(:user_id, User.all.collect {|u| [u.first_name, u.id]},{},:prompt => "Select User",:class=>"form-control") %>
        
          </div>
        </div><br><br><br><br>

      <div class="form-group">
        <label class="col-sm-3 control-label">Region</label>
        <div class="col-sm-6  inputGroupContainer">
        <%= f.select(:region_id, Region.find(Region.ids - UserRegion.all.map(&:region_id).uniq).collect {|u| [u.region_name, u.id]},{},:prompt => 'Select Region',:class=>"form-control") %>  

       </div>
       </div>
      
       <div class="form-group">
              <label class="col-sm-2 control-label"></label>
              <div class="col-sm-6 inputGroupContainer">
           <%#=link_to 'add',:id=>'xyz'%>
            </div>
        </div>


             <div class="form-group">
              <label class="col-sm-1 control-label"></label>
              <div class="col-sm-2  inputGroupContainer">
           <%#=link_to 'remove',:id=>'xyz1'%>
            </div>
        </div> 

       <div class="form-group">
        <label class="col-sm-1 control-label"></label>
        <div class="col-sm-1  inputGroupContainer">
       <%#= f.text_area :text, value: "aaa", :size => "20x5" %>
       <!-- <ul>
        <% UserRegion.all.each do  |region| %>
         <% if region.right == "true" %>
         <li>
              <%= Region.find(region.region_id).region_name%>
         </li>
        <% end %>

        <% end %>
       </ul> -->
  </div>
  </div> <br><br>
       
     
  <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
          <%=f.submit "Add", :class=>"btn btn-success" %>
        </div>
      </div>
<% end %>

</div>
</div>

<div class="col-sm-6">
<%= form_for(user_region, :remote=>true) do |f| %>
  <% if user_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_region.errors.count, "error") %> prohibited this user_region from being saved:</h2>

      <ul>
      <% user_region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %><br><br><br><br>
  

  
      <div class="form-group">
        <label class="col-sm-2 control-label">Region</label>
        <div class="col-sm-6  inputGroupContainer">
        <%= f.select(:region_id, Region.find(UserRegion.all.map(&:region_id).uniq).collect {|u| [u.region_name, u.id]},{},:prompt => 'Select Region',:class=>"form-control") %>  

       </div>
       </div>
      
       <div class="form-group">
              <label class="col-sm-1 control-label"></label>
              <div class="col-sm-1  inputGroupContainer">
           <%= f.hidden_field :right_value, :value => "xyz" %> <%= f.hidden_field :right_value, :value => "xyz" %> <%= f.hidden_field :right_value, :value => "xyz" %> <%= f.hidden_field :right_value, :value => "xyz" %>
            </div>
        </div>


           
       
     
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
          <%=f.submit "Remove", :class=>"btn btn-success" %>
        </div>
      </div><br><br><br>
    <% end %>
  </div>
</div>

app/views/user_regions/_form1.html.erb
 <div class="Container">
<%= form_for user_region do |f| %>
  <% if user_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_region.errors.count, "error") %> prohibited this user_region from being saved:</h2>

      <ul>
      <% user_region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-3  inputGroupContainer">
        <%=f.select(:user_id, User.all.collect {|u| [u.first_name, u.id]},{},:prompt => "Select User",:class=>"form-control") %>
        
          </div>
        </div><br><br><br><br>

      <div class="form-group">
        <label class="col-sm-2 control-label">Region</label>
        <div class="col-sm-3  inputGroupContainer">
        <%= f.select(:region_name, UserRegion.find(UserRegion.id - Region.all.map(&:id).uniq).collect {|u| [u.region_name, u.id]},{},:prompt => 'Select Region',:class=>"form-control") %>  

       </div>
       </div>
      
       <div class="form-group">
              <label class="col-sm-1 control-label"></label>
              <div class="col-sm-1  inputGroupContainer">
           <%=link_to 'add',:id=>'xyz'%>
            </div>
        </div>


             <div class="form-group">
              <label class="col-sm-1 control-label"></label>
              <div class="col-sm-1  inputGroupContainer">
           <%=link_to 'remove',:id=>'xyz1'%>
            </div>
        </div> 

       <div class="form-group">
        <label class="col-sm-1 control-label"></label>
        <div class="col-sm-2  inputGroupContainer">
       <%#= f.text_area :text, value: "aaa", :size => "20x5" %>
       <ul>
        <% UserRegion.all.each do  |region| %>
         <% if region.left == "true" %>
         <li>
              <%= UserRegion.find(region.region_id).region_name%>
         </li>
        <% end %>

        <% end %>
       </ul>
  </div>
  </div> <br><br>
       
     
  <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
          <%=f.submit "save", :class=>"btn btn-success" %>
        </div>
      </div>
<% end %>

</div>

app/views/user_regions/_index.html.erb
 <p id="notice"><%= notice %></p>
<div class="user_region-container">
<h1>User Regions</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Region</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_regions.each do |user_region| %>
      <tr> 

        <td><%if user_region.user_id.present? %> 
      <%= User.find(user_region.user_id).first_name %> 
         <% end %> </td>
        <td><%if user_region.region_id.present?%>
  <%= Region.find(user_region.region_id).region_name %>
     <%end%></td>
        <td><%= link_to 'Show',  show_page_user_region_path(user_region),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit', edit_user_region_user_region_path(user_region),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', user_region, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/user_regions/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%if @user_region.user_id.present? %> 
  <%= User.find(@user_region.user_id).first_name %> 
    <% end %> 
</p>

<p>
  <strong>Region:</strong>
 <%if @user_region.region_id.present?%>
  <%= Region.find(@user_region.region_id).region_name %>
<%end%>
</p>

app/views/user_regions/edit.html.erb
<h1>Editing User Region</h1>

<%= render 'form', user_region: @user_region %>

<%= link_to 'Show', @user_region %> |
<%= link_to 'Back', user_regions_path %>

app/views/user_regions/edit_user_region.js.erb
$('.modal-body').html('<%= escape_javascript(render "form", user_region: @user_region )%>');

app/views/user_regions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="user_region-container">
<h1>User Regions</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Region</th>
       <th>Like</th>
        <th>Dislike</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_regions.each do |user_region| %>
      <tr> 

        <td><%if user_region.user_id.present? %> 
      <%= User.find(user_region.user_id).first_name %> 
         <% end %> </td>
        <td><%if user_region.region_id.present?%>
  <%= Region.find(user_region.region_id).region_name %>
     <%end%></td>
      <div class="col-md-6">
         <div class="btn-group pull-right" style="">
           <td><%= link_to like_user_region_path(user_region), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
            <span class="glyphicon glyphicon-thumbs-up user_region-up-<%=user_region.id%>" style='width: 50px' >
             <%= user_region.get_upvotes.size %> <% end %></td>
            </span>

           <td><%= link_to dislike_user_region_path(user_region), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
           <span class="glyphicon glyphicon-thumbs-down user_region-down-<%=user_region.id%>" style='width: 50px'>
             <%= user_region.get_downvotes.size %><% end %></td>
           </span>
         </div>
       </div>

        <td><%= link_to 'Show',  show_page_user_region_path(user_region),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit', edit_user_region_user_region_path(user_region),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        
        <td><%= link_to 'Destroy', user_region, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Region', new_user_region_path %>
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title">User Region Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>
 
 <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title"> update User Region Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>

app/views/user_regions/new.html.erb
<center><h1> User to Region</h1></center>

<%= render 'form', user_region: @user_region %>
<div class="form-group">
        <label class="col-sm-1 control-label"></label>
        <div class="col-sm-2">
<%= link_to 'Back', user_regions_path,:class=>"btn btn-info" %>
</div>
</div>

app/views/user_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%if @user_region.user_id.present? %> 
  <%= User.find(@user_region.user_id).first_name %> 
    <% end %> 
</p>

<p>
  <strong>Region:</strong>
 <%if @user_region.region_id.present?%>
  <%= Region.find(@user_region.region_id).region_name %>
<%end%>
</p>

<% @user_region.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body%>
  </p> 
  <div class="btn-group pull-right">
         <td><%= link_to like_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-up comment-up-<%=comment.id%>" style='width: 50px'>
             <%= comment.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-down comment-down-<%=comment.id%>" style='width: 50px'>
           <%= comment.get_downvotes.size %><% end %></td>
          </span>
      </div> 
<%end%>

<h2>Add a comment:</h2>

<%= form_for @comment, :url =>comments_user_region_path , :method =>"post"  do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter%>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>
<%= link_to 'Edit', edit_user_region_path(@user_region) %> |
<%= link_to 'Back', user_regions_path %>

app/views/user_regions/show_page.js.erb
$(".modal-body").html("<%= escape_javascript(render 'user_regions/show') %>");

app/views/user_regions/update_user_regions.js.erb
$('.user_region-container').html('<%= escape_javascript( render "user_regions/index")%>');
$("#myModal1").modal('hide');

app/views/user_regions/user_regions.js.erb
$(function() 
	{ $('.user_region-up-<%=@user_region.id%>').text("<%= @user_region.get_upvotes.size %>");
 $('.user_region-down-<%=@user_region.id%>').text("<%= @user_region.get_downvotes.size %>"); });