config/routes.rb
# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)
#   resources :nodes
#   resources :places
#   resources :images
#   resources :cities do
#     collection do
#       get :get_cities
#     end
#   end

#   resources :states do
#     collection do
#       get :get_states
#     end
#   end 
#   resources :countries
#   resources :regions
#   resources :user_regions
#   resources :user_roles
#   devise_for :users
#   resources :companies
#   resources :managers 
#   root'companies#index'
 
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  resources :regions do
    member do 
      get :edit_region
      get :show_page
      post :comments
      put "like", to: "regions#upvote"
      put "dislike", to: "regions#downvote"
    end
  end

  resources :nodes do
    member do 
      get :edit_node
    end 
    member do
      get :show_page
    end
   end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :places do
    member do 
      get :edit_place
      get :show_page
      post :comments
      put "like", to: "places#upvote"
      put "dislike", to: "places#downvote"
    end
  end

  resources :images do
    collection do 
      get :login_page
    end 
  end
  

  resources :cities do
    collection do
      get :get_cities
    end
    member do
      get :show_page
      get :edit_city
      post :comments
      put "like", to: "cities#upvote"
      put "dislike", to: "cities#downvote"
    end
  end 

  resources :states do
    collection do
      get :get_states
    end
    member do 
      get :edit_state
      get :show_page
      post :comments
      put "like", to: "states#upvote"
      put "dislike", to: "states#downvote"
    end
  end 

  resources :countries do
    member do
      get :edit_country
      get :show_page
      post :comments
      put "like", to: "countries#upvote"
      put "dislike", to: "countries#downvote"
    end
  end

  resources :user_regions do
    member do 
      get :edit_user_region
      get :show_page
      post :comments
       put "like", to: "user_regions#upvote"
      put "dislike", to: "user_regions#downvote"
    end
  end

  resources :user_roles do
   member do 
      get :edit_user_role
      get :show_page
      post :comments
       put "like", to: "user_roles#upvote"
      put "dislike", to: "user_roles#downvote"
    end
  end

  resources :companies do
    resources :comments
     member do
      put "like", to: "companies#upvote"
      put "dislike", to: "companies#downvote"
    end 
  
    member do 
      get :edit_company
      get :show_page
    end 
    
  end
  
  resources :managers do
    member do
      get :show_page
      get :edit_manager
      
    end
  end

 resources :comments, only: [] do
   member do 
     put "like", to: "comments#upvote" 
     put "dislike", to: "comments#downvote" 
    end 
  end
  

  devise_for :users
  root 'companies#index'
  # get 'get_states' => "states#get_states"
  #  get 'get_cities' => "cities#get_cities"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/city.rb
class City < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  acts_as_votable
  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
	
	acts_as_commentable
	acts_as_votable
     #has_many :comments
	has_many :countries
	has_many :states
	has_many :cities
end

app/models/country.rb
class Country < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_many :states
	has_many :cities
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, :polymorphic => true
	mount_uploader :image_name, ImageUploader
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_one :node
	attr_accessor :node_name
end

app/models/region.rb
class Region < ApplicationRecord
	acts_as_commentable
   acts_as_votable
 has_many :regions, through: :user_regions 
  has_many :users, through: :user_regions

end

app/models/state.rb
class State < ApplicationRecord
	acts_as_commentable
	acts_as_votable
	has_many :cities
end

app/models/user.rb
class User < ApplicationRecord
	has_many :regions, through: :user_regions 
	has_many :images, :as=> :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
	acts_as_commentable
	acts_as_votable
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy,:show_page,:edit_place]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @commentable=Place.find(params[:id])
    @comment=Comment.new
  end
   def show_page
   render 'places/show_page'
  end

  # GET /places/new
  def new
    @place = Place.new
  end
   
   
  def edit
  end
    
  def upvote
   @place = Place.find(params[:id])
    @place.upvote_by current_user
    respond_to do |format|
      format.js { render :file=>  'places/places.js.erb'}
    end
  end

  def downvote
   @place = Place.find(params[:id])
    @place.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :file=> 'places/places.js.erb'}
    end
  end 
  # GET /places/1/edit
  def comments
    @commentable=Place.find(params[:id])
    @comment=@commentable.comments.create(comment_params)
    @comment.save
    redirect_to place_path
  end
  def edit_place
     render 'places/edit_place'
    end

  # POST /places
  # POST /places.json
  def create
    
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
          Node.create(:node_name=> params[:place][:node_name])


        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        @places = Place.all
        format.js { render :file=>'places/update_places.js.erb', notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end
     def comment_params
      params.require(:comment).permit(:commenter,:body)
     end
    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:place_name, :company_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/places/_form.html.erb
<div class="Container">
<%= form_for(place, :remote=>true) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

   <div class="form-group">
      <label class="col-sm-2 control-label">PlaceName</label>
      <div class="col-sm-6  inputGroupContainer">
        
       <%= f.text_field :place_name, :placeholder=>"PlaceName", :class=>"form-control",required: true %>
      </div>
    </div><br><br><br>

   <!--  <div class="form-group">
      <label class="col-sm-1 control-label">Node Name</label>
      <div class="col-sm-6  inputGroupContainer">
        
       <%#= f.text_field :node_name, :placeholder=>"NodeName", :class=>"form-control" %>
      </div>
    </div><br><br><br> -->

    <div class="form-group">
      <label class="col-sm-2 control-label">Company</label>
      <div class="col-sm-3  inputGroupContainer">
        <%=f.select(:company_id, Company.all.collect {|u| [u.name, u.id]},:prompt => "Select Company") %>
      </div>
    </div>

       
     
  <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
          <%=f.submit :class=>"btn btn-success" %>
        </div>
      </div>
<% end %>

</div>

app/views/places/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="place-container">
<h1>Places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Place name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.place_name %></td>
        <td><%if place.company_id.present? %> 
         <%= Company.find(place.company_id).name %> 
         <%end %>
        </td>
        <td><%= link_to 'Show', show_page_place_path(place),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit',  edit_place_place_path(place),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/places/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place name:</strong>
  <%= @place.place_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @place.company_id %>
</p>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/edit_place.js.erb
$('.modal-body').html('<%= escape_javascript(render "form", place: @place )%>');

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<div class="place-container">
<h1>Places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Place name</th>
      <th>Company</th>
      <th>Like</th>
      <th>DisLike</th>
    
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.place_name %></td>
        <td><%if place.company_id.present? %> 
         <%= Company.find(place.company_id).name %> 
         <%end %>
        </td>
        <div class="col-md-6">
          <div class="btn-group pull-right" style="">
         <td><%= link_to like_place_path(place), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
          <span class="glyphicon glyphicon-thumbs-up place-up-<%=place.id%>" style='width: 50px' >
             <%= place.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_place_path(place), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>
          <span class="glyphicon glyphicon-thumbs-down place-down-<%=place.id%>" style='width: 50px'>
           <%= place.get_downvotes.size %><% end %></td>
          </span>
      </div>
    </div>

        <td><%= link_to 'Show',  show_page_place_path(place),:class=>"btn btn-info",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal' %></td>

        <td><%= link_to 'Edit', edit_place_place_path(place),:class=>"btn btn-warning",:remote => true, 'data-toggle' =>"modal",'data-target' =>'#myModal1' %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path,:class=>"btn btn-success" %>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title">Place Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>
 
 <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title"> update Place Info</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
       <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
     </div>
    </div>
</div>

app/views/places/new.html.erb
<h1>Add Place</h1>

<%= render 'form', place: @place %>
<div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
<%= link_to 'Back', places_path %>
</div>
</div>

app/views/places/places.js.erb
$(function() 
	{ $('.place-up-<%=@place.id%>').text("<%= @place.get_upvotes.size %>");
 $('.place-down-<%=@place.id%>').text("<%= @place.get_downvotes.size %>"); });

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place name:</strong>
  <%= @place.place_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @place.company_id %>
</p>


<h2>Comments</h2>

<% @place.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body%>
  </p> 
  <div class="btn-group pull-right">
         <td><%= link_to like_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-up comment-up-<%=comment.id%>" style='width: 50px'>
             <%= comment.get_upvotes.size %> <% end %></td>
          </span>

          <td><%= link_to dislike_comment_path(comment), method: :put ,data: { :remote=> true } , :class=> "btn btn-default" do %>

          <span class="glyphicon glyphicon-thumbs-down comment-down-<%=comment.id%>" style='width: 50px'>
           <%= comment.get_downvotes.size %><% end %></td>
          </span>
      </div> 
<%end%>

<h2>Add a comment:</h2>

<%= form_for @comment, :url =>comments_place_path , :method =>"post"  do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter%>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/places/show_page.js.erb
$(".modal-body").html("<%= escape_javascript(render 'places/show') %>");

app/views/places/update_places.js.erb
$('.place-container').html('<%= escape_javascript( render "places/index")%>');
$("#myModal1").modal('hide');